# Install in /etc/nginx/conf.d/. These directives belong to the http context.
upstream casandra_web_api {
    server 127.0.0.1:8010;
    keepalive 2;
}

map $request_method $casandra_upload_addr {
    default "";
    POST $proxy_protocol_addr;
}
map $request_method $casandra_upload_global {
    default "";
    POST $server_name;
}

limit_conn_zone $proxy_protocol_addr zone=casandra_client_connections:10m;
limit_conn_zone $server_name zone=casandra_global_connections:1m;
limit_conn_zone $casandra_upload_addr zone=casandra_client_uploads:10m;
limit_conn_zone $casandra_upload_global zone=casandra_global_uploads:1m;
limit_req_zone $proxy_protocol_addr zone=casandra_client_requests:10m rate=5r/s;
limit_req_zone $server_name zone=casandra_global_requests:1m rate=10r/s;
limit_req_zone $casandra_upload_addr zone=casandra_submissions:10m rate=1r/m;
