import { isAbstained, decisionLabel, reasonLabel } from "./specificity.js";
import { asArray, classificationMethodLabel, evidenceScore } from "./formatting.js";

const numericValue = (value) => {
  if (!["number", "string"].includes(typeof value) || String(value).trim() === "") return null;
  const number = Number(value);
  return Number.isFinite(number) ? number : null;
};
export const tableNumber = (value) => numericValue(value)?.toLocaleString() ?? "—";
export const tablePosition = (row) => `${tableNumber(row.start)}–${tableNumber(row.end)}`;
export const familyLabel = (row) => {
  if (isAbstained(row)) return "Withheld Cas evidence";
  if (row?.decision_status === "baseline_negative") return "Original-core negative";
  if (row?.is_cas === false || String(row?.result).toLowerCase() === "no cas") return "no cas";
  return row?.cas_family || row?.result || row?.profile || "Not reported";
};

// Only shorten identifiers generated by this pipeline; submitted identifiers stay intact.
export function featureLabel(id) {
  if (typeof id !== "string" || !id.startsWith("casandra|")) return id || "Not reported";
  const match = id.match(/\|(cds|cassette|array)=(\d+)(?:\||$)/);
  if (!match) return id;
  return `${{ cds: "CDS", cassette: "Cassette", array: "Array" }[match[1]]} ${Number(match[2])}`;
}

export function partialEnds(row) {
  if (typeof row.partial_5prime !== "boolean" || typeof row.partial_3prime !== "boolean") return "Not fully reported";
  if (row.partial_5prime && row.partial_3prime) return "5′ and 3′";
  if (row.partial_5prime) return "5′";
  if (row.partial_3prime) return "3′";
  return "Neither end";
}

const datum = (label, value, extra = {}) => ({ label, value: value ?? "Not reported", ...extra });
const systemContext = (row) => [row.class && `Class ${row.class}`, row.type && `Type ${row.type}`, row.subtype].filter(Boolean).join(" · ") || "Not reported";
const score = (value, probability = false) => evidenceScore(numericValue(value) ?? undefined, probability === true);
export const sourceId = (row) => row.contig_id || row.sequence_id || null;
const positionCell = (row, showSource) => ({ text: tablePosition(row), note: sourceId(row) ? (showSource ? sourceId(row) : null) : "Source not reported" });

export function proteinEvidence(row, genomic = false) {
  return [
    ...(row.decision_status ? [datum("Decision", decisionLabel(row)), datum("Reason", reasonLabel(row)), datum("Original-core family", row.core_original_prediction?.cas_family, { note: "Evidence before specificity rules; not a final annotation." })] : []),
    datum("Protein ID", row.protein_id, { code: true, wide: true }),
    ...(genomic ? [datum("Source record", sourceId(row), { code: true })] : []),
    datum("Profile", row.profile, { code: true }),
    datum("Profile score", row.profile === null ? "No positive hit; stored sentinel is not observed evidence" : score(row.profile_score, row.score_is_probability)),
    datum(row.decision_status ? "Original-core margin" : "Score margin", score(row.score_margin), { note: row.score_interpretation }),
    datum("Hard-negative score", row.hard_negative_hit_present === false ? "No hit; stored sentinel is not observed evidence" : score(row.hard_negative_profile_score)),
    datum("Profile context", row.is_cas === false ? "Not applicable" : systemContext(row), { note: "Supplementary profile annotation; not a cassette classification." }),
    ...(genomic ? [datum("Genetic code", tableNumber(row.translation_table)), datum("Partial CDS ends", partialEnds(row))] : []),
  ];
}

function gateLabel(gate) {
  if (gate === true || gate === "passed" || gate?.accepted === true) return "Accepted";
  if (gate === false || gate?.accepted === false) return "Not accepted";
  return typeof gate === "string" ? gate : "Not reported";
}

export function cassetteEvidence(row, arraysRequested = false) {
  const gate = row.evidence_gate;
  const nearest = row.nearest_array;
  return [
    ...(row.cassette_id ? [datum("Cassette ID", row.cassette_id, { code: true, wide: true }), datum("Source record", sourceId(row), { code: true })] : []),
    datum("Classification", systemContext(row)),
    datum("Method", classificationMethodLabel(row.method)),
    datum("Method ID", row.method, { code: true }),
    datum("Classification score", score(row.confidence, row.confidence_is_probability)),
    datum("Evidence gate", gateLabel(gate)),
    ...(gate?.rule ? [datum("Gate rule", gate.rule, { code: true })] : []),
    ...(arraysRequested ? [datum("Nearest array", nearest?.array_id || "None reported", { code: Boolean(nearest?.array_id), note: nearest?.array_id ? `Distance: ${tableNumber(nearest.distance_bp)} bp. Coordinate proximity only.` : null })] : []),
  ];
}

export function cassetteMembers(cassette, proteins, genomic = true) {
  const byId = new Map(proteins.map((row) => [row.protein_id, row]));
  const ids = asArray(cassette.cas_protein_ids);
  const members = ids.map((id) => byId.get(id));
  // Sort only complete joins with reported coordinates; never infer positions from IDs.
  if (genomic && members.length && members.every((row) => row && numericValue(row.start) !== null)) {
    members.sort((a, b) => numericValue(a.start) - numericValue(b.start));
  }
  const missing = Math.max(0, (numericValue(cassette.cas_gene_count) ?? ids.length) - ids.length);
  return {
    items: members.map((row) => row ? familyLabel(row) : "Family unavailable"),
    note: missing ? `${missing} member ${missing === 1 ? "annotation" : "annotations"} unavailable` : null,
  };
}

export function cassetteRows(cassettes, proteins, showSource, arraysRequested) {
  return cassettes.map((row) => ({
    id: row.cassette_id,
    label: `${featureLabel(row.cassette_id)}${sourceId(row) ? ` on ${sourceId(row)}` : ""}`,
    cells: {
      name: { text: featureLabel(row.cassette_id) },
      subtype: { text: row.subtype || row.type || "Unresolved", tone: "cas" },
      position: positionCell(row, showSource),
      count: { text: tableNumber(row.cas_gene_count) },
      families: cassetteMembers(row, proteins),
      score: { text: score(row.confidence, row.confidence_is_probability) },
    },
    details: [...cassetteEvidence(row, arraysRequested), datum("Cas protein IDs", asArray(row.cas_protein_ids).join(" · ") || "Not reported", { code: true, wide: true })],
  }));
}

export function geneRows(proteins, showSource) {
  return proteins.map((row) => ({
    id: row.protein_id,
    label: `${featureLabel(row.protein_id)}${sourceId(row) ? ` on ${sourceId(row)}` : ""}`,
    cells: {
      name: { text: featureLabel(row.protein_id) },
      family: { text: familyLabel(row), tone: row.is_cas === false ? "not-cas" : "cas" },
      position: positionCell(row, showSource),
      strand: { text: ["+", "-"].includes(row.strand) ? row.strand : "?", accessible: row.strand === "+" ? "plus strand" : row.strand === "-" ? "minus strand" : "strand not reported" },
      cassette: { text: row.cassette_id ? featureLabel(row.cassette_id) : "Not assigned" },
      score: { text: row.profile === null ? "No positive hit" : score(row.profile_score, row.score_is_probability) },
    },
    details: [...proteinEvidence(row, true), datum("Cassette ID", row.cassette_id || "Not assigned", { code: Boolean(row.cassette_id), wide: true })],
  }));
}

export function predictionRows(predictions) {
  return predictions.map((row) => ({
    id: row.protein_id,
    label: row.protein_id,
    cells: {
      name: { text: row.protein_id },
      family: { text: familyLabel(row), tone: row.is_cas === false ? "not-cas" : "cas" },
      length: { text: tableNumber(row.residue_count) },
      score: { text: row.profile === null ? "No positive hit" : score(row.profile_score, row.score_is_probability) },
    },
    details: proteinEvidence(row),
  }));
}

export function arrayRows(arrays, showSource) {
  return arrays.map((row) => ({
    id: JSON.stringify([sourceId(row), row.array_id]),
    label: `${featureLabel(row.array_id)}${sourceId(row) ? ` on ${sourceId(row)}` : ""}`,
    cells: {
      name: { text: featureLabel(row.array_id) },
      position: positionCell(row, showSource),
      strand: { text: ["+", "-"].includes(row.strand) ? row.strand : "?", accessible: row.strand === "+" ? "plus strand" : row.strand === "-" ? "minus strand" : "strand not reported" },
      category: { text: row.category || "Unclassified" },
      repeats: { text: tableNumber(row.repeat_count) },
      spacers: { text: tableNumber(row.spacer_count) },
    },
    details: [datum("Array ID", row.array_id, { code: true, wide: true }), datum("Source record", sourceId(row), { code: true }), datum("Model score", score(row.model_score, row.model_score_is_probability))],
  }));
}
